#!/bin/bash
#SBATCH --array=0-95%10
#SBATCH --error=/cluster/tufts/hugheslab/eharve06/slurmlog/err/log_%j.err
#SBATCH --gres=gpu:a100:1
#SBATCH --mem=64g
#SBATCH --nodelist=cc1gpu[001,003,004,005]
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --output=/cluster/tufts/hugheslab/eharve06/slurmlog/out/log_%j.out
#SBATCH --partition=gpu
#SBATCH --time=48:00:00

source ~/.bashrc
conda activate l3d_2024f_cuda12_1

# Define an array of commands
experiments=(
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=100_random_state=1001" --n=100 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=100_random_state=1001" --n=100 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=100_random_state=1001" --n=100 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=100_random_state=1001" --n=100 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=100_random_state=2001" --n=100 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=100_random_state=2001" --n=100 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=100_random_state=2001" --n=100 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=100_random_state=2001" --n=100 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=100_random_state=3001" --n=100 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=100_random_state=3001" --n=100 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=100_random_state=3001" --n=100 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=100_random_state=3001" --n=100 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'



    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=1000_random_state=1001" --n=1000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=1000_random_state=1001" --n=1000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=1000_random_state=1001" --n=1000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=1000_random_state=1001" --n=1000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=1000_random_state=2001" --n=1000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=1000_random_state=2001" --n=1000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=1000_random_state=2001" --n=1000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=1000_random_state=2001" --n=1000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=1000_random_state=3001" --n=1000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=1000_random_state=3001" --n=1000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=1000_random_state=3001" --n=1000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=1000_random_state=3001" --n=1000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    
    
    
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=10000_random_state=1001" --n=10000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=10000_random_state=1001" --n=10000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=10000_random_state=1001" --n=10000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=10000_random_state=1001" --n=10000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=10000_random_state=2001" --n=10000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=10000_random_state=2001" --n=10000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=10000_random_state=2001" --n=10000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=10000_random_state=2001" --n=10000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=10000_random_state=3001" --n=10000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=10000_random_state=3001" --n=10000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=10000_random_state=3001" --n=10000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=10000_random_state=3001" --n=10000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    
    
    
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=50000_random_state=1001" --n=50000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=50000_random_state=1001" --n=50000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=50000_random_state=1001" --n=50000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=50000_random_state=1001" --n=50000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=50000_random_state=2001" --n=50000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=50000_random_state=2001" --n=50000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=50000_random_state=2001" --n=50000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=50000_random_state=2001" --n=50000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=50000_random_state=3001" --n=50000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=50000_random_state=3001" --n=50000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=50000_random_state=3001" --n=50000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="CIFAR-10" --dataset_dir="/cluster/tufts/hugheslab/eharve06/CIFAR-10" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_CIFAR-10_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=50000_random_state=3001" --n=50000 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    
    
    
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=510_random_state=1001" --n=510 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=510_random_state=1001" --n=510 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=510_random_state=1001" --n=510 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=510_random_state=1001" --n=510 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=510_random_state=2001" --n=510 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=510_random_state=2001" --n=510 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=510_random_state=2001" --n=510 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=510_random_state=2001" --n=510 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=510_random_state=3001" --n=510 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=510_random_state=3001" --n=510 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=510_random_state=3001" --n=510 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=510_random_state=3001" --n=510 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'

    
    
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=1020_random_state=1001" --n=1020 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=1020_random_state=1001" --n=1020 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=1020_random_state=1001" --n=1020 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=1020_random_state=1001" --n=1020 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=1020_random_state=2001" --n=1020 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=1020_random_state=2001" --n=1020 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=1020_random_state=2001" --n=1020 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=1020_random_state=2001" --n=1020 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=1020_random_state=3001" --n=1020 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=1020_random_state=3001" --n=1020 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=1020_random_state=3001" --n=1020 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Flower-102" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Flower-102" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Flower-102_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=1020_random_state=3001" --n=1020 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'



    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=370_random_state=1001" --n=370 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=370_random_state=1001" --n=370 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=370_random_state=1001" --n=370 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=370_random_state=1001" --n=370 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=370_random_state=2001" --n=370 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=370_random_state=2001" --n=370 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=370_random_state=2001" --n=370 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=370_random_state=2001" --n=370 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=370_random_state=3001" --n=370 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=370_random_state=3001" --n=370 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=370_random_state=3001" --n=370 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=370_random_state=3001" --n=370 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    
    
    
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=3441_random_state=1001" --n=3441 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=3441_random_state=1001" --n=3441 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=3441_random_state=1001" --n=3441 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=3441_random_state=1001" --n=3441 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=1001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=3441_random_state=2001" --n=3441 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=3441_random_state=2001" --n=3441 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=3441_random_state=2001" --n=3441 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=3441_random_state=2001" --n=3441 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=2001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.1 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.1_n=3441_random_state=3001" --n=3441 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.01 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.01_n=3441_random_state=3001" --n=3441 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.001_n=3441_random_state=3001" --n=3441 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
    'python ../src/main_image_classifiers_laplace.py --batch_size=128 --dataset="Pet-37" --dataset_dir="/cluster/tufts/hugheslab/eharve06/Pet-37" --experiments_dir="/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_Pet-37_ConvNeXt-Tiny_diagEF" --la_batch_size=64 --lr_0=0.0001 --model_arch="ConvNeXt-Tiny" --model_name="l2-sp_lr_0=0.0001_n=3441_random_state=3001" --n=3441 --num_workers=0 --prior_dir="/cluster/tufts/hugheslab/eharve06/convnext_tiny_torchvision" --prior_type="convnext_tiny_torchvision" --random_state=3001 --save'
)

eval "${experiments[$SLURM_ARRAY_TASK_ID]}"

conda deactivate
