#!/bin/bash
#SBATCH --array=20-59%20
#SBATCH --error=/cluster/tufts/hugheslab/eharve06/slurmlog/err/log_%j.err
#SBATCH --gres=gpu:a100:1
#SBATCH --mem=64g
#SBATCH --nodes=1
#SBATCH --nodelist=cc1gpu[001,003,004,005]
#SBATCH --ntasks=4
#SBATCH --output=/cluster/tufts/hugheslab/eharve06/slurmlog/out/log_%j.out
#SBATCH --partition=ccgpu
#SBATCH --time=48:00:00

source ~/.bashrc
conda activate l3d_2024f_cuda12_1

# Define an array of commands
experiments=(
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.1 --model_name='l2-sp_lr_0=0.1_n=40_random_state=1001' --n=40 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.1 --model_name='l2-sp_lr_0=0.1_n=40_random_state=2001' --n=40 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.1 --model_name='l2-sp_lr_0=0.1_n=40_random_state=3001' --n=40 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.01 --model_name='l2-sp_lr_0=0.01_n=40_random_state=1001' --n=40 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.01 --model_name='l2-sp_lr_0=0.01_n=40_random_state=2001' --n=40 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.01 --model_name='l2-sp_lr_0=0.01_n=40_random_state=3001' --n=40 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.001 --model_name='l2-sp_lr_0=0.001_n=40_random_state=1001' --n=40 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.001 --model_name='l2-sp_lr_0=0.001_n=40_random_state=2001' --n=40 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.001 --model_name='l2-sp_lr_0=0.001_n=40_random_state=3001' --n=40 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.0001 --model_name='l2-sp_lr_0=0.0001_n=40_random_state=1001' --n=40 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.0001 --model_name='l2-sp_lr_0=0.0001_n=40_random_state=2001' --n=40 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.0001 --model_name='l2-sp_lr_0=0.0001_n=40_random_state=3001' --n=40 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.1 --model_name='l2-sp_lr_0=0.1_n=400_random_state=1001' --n=400 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.1 --model_name='l2-sp_lr_0=0.1_n=400_random_state=2001' --n=400 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.1 --model_name='l2-sp_lr_0=0.1_n=400_random_state=3001' --n=400 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.01 --model_name='l2-sp_lr_0=0.01_n=400_random_state=1001' --n=400 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.01 --model_name='l2-sp_lr_0=0.01_n=400_random_state=2001' --n=400 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.01 --model_name='l2-sp_lr_0=0.01_n=400_random_state=3001' --n=400 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.001 --model_name='l2-sp_lr_0=0.001_n=400_random_state=1001' --n=400 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.001 --model_name='l2-sp_lr_0=0.001_n=400_random_state=2001' --n=400 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.001 --model_name='l2-sp_lr_0=0.001_n=400_random_state=3001' --n=400 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.0001 --model_name='l2-sp_lr_0=0.0001_n=400_random_state=1001' --n=400 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.0001 --model_name='l2-sp_lr_0=0.0001_n=400_random_state=2001' --n=400 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.0001 --model_name='l2-sp_lr_0=0.0001_n=400_random_state=3001' --n=400 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.1 --model_name='l2-sp_lr_0=0.1_n=4000_random_state=1001' --n=4000 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.1 --model_name='l2-sp_lr_0=0.1_n=4000_random_state=2001' --n=4000 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.1 --model_name='l2-sp_lr_0=0.1_n=4000_random_state=3001' --n=4000 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.01 --model_name='l2-sp_lr_0=0.01_n=4000_random_state=1001' --n=4000 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.01 --model_name='l2-sp_lr_0=0.01_n=4000_random_state=2001' --n=4000 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.01 --model_name='l2-sp_lr_0=0.01_n=4000_random_state=3001' --n=4000 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.001 --model_name='l2-sp_lr_0=0.001_n=4000_random_state=1001' --n=4000 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.001 --model_name='l2-sp_lr_0=0.001_n=4000_random_state=2001' --n=4000 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.001 --model_name='l2-sp_lr_0=0.001_n=4000_random_state=3001' --n=4000 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.0001 --model_name='l2-sp_lr_0=0.0001_n=4000_random_state=1001' --n=4000 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.0001 --model_name='l2-sp_lr_0=0.0001_n=4000_random_state=2001' --n=4000 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.0001 --model_name='l2-sp_lr_0=0.0001_n=4000_random_state=3001' --n=4000 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.1 --model_name='l2-sp_lr_0=0.1_n=40000_random_state=1001' --n=40000 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.1 --model_name='l2-sp_lr_0=0.1_n=40000_random_state=2001' --n=40000 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.1 --model_name='l2-sp_lr_0=0.1_n=40000_random_state=3001' --n=40000 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.01 --model_name='l2-sp_lr_0=0.01_n=40000_random_state=1001' --n=40000 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.01 --model_name='l2-sp_lr_0=0.01_n=40000_random_state=2001' --n=40000 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.01 --model_name='l2-sp_lr_0=0.01_n=40000_random_state=3001' --n=40000 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.001 --model_name='l2-sp_lr_0=0.001_n=40000_random_state=1001' --n=40000 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.001 --model_name='l2-sp_lr_0=0.001_n=40000_random_state=2001' --n=40000 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.001 --model_name='l2-sp_lr_0=0.001_n=40000_random_state=3001' --n=40000 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.0001 --model_name='l2-sp_lr_0=0.0001_n=40000_random_state=1001' --n=40000 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.0001 --model_name='l2-sp_lr_0=0.0001_n=40000_random_state=2001' --n=40000 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.0001 --model_name='l2-sp_lr_0=0.0001_n=40000_random_state=3001' --n=40000 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.1 --model_name='l2-sp_lr_0=0.1_n=120000_random_state=1001' --n=120000 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.1 --model_name='l2-sp_lr_0=0.1_n=120000_random_state=2001' --n=120000 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.1 --model_name='l2-sp_lr_0=0.1_n=120000_random_state=3001' --n=120000 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.01 --model_name='l2-sp_lr_0=0.01_n=120000_random_state=1001' --n=120000 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.01 --model_name='l2-sp_lr_0=0.01_n=120000_random_state=2001' --n=120000 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.01 --model_name='l2-sp_lr_0=0.01_n=120000_random_state=3001' --n=120000 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.001 --model_name='l2-sp_lr_0=0.001_n=120000_random_state=1001' --n=120000 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.001 --model_name='l2-sp_lr_0=0.001_n=120000_random_state=2001' --n=120000 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.001 --model_name='l2-sp_lr_0=0.001_n=120000_random_state=3001' --n=120000 --num_workers=0 --random_state=3001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.0001 --model_name='l2-sp_lr_0=0.0001_n=120000_random_state=1001' --n=120000 --num_workers=0 --random_state=1001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.0001 --model_name='l2-sp_lr_0=0.0001_n=120000_random_state=2001' --n=120000 --num_workers=0 --random_state=2001 --save"
    "python ../src/fine-tuning_AG_News-Copy1.py --batch_size=32 --criterion='l2-sp' --dataset_directory='/cluster/tufts/hugheslab/eharve06/AG_News' --experiments_directory='/cluster/tufts/hugheslab/eharve06/data-emphasized-ELBo/experiments/retrained_AG_News_diagEF_F=1_SGD' --lr_0=0.0001 --model_name='l2-sp_lr_0=0.0001_n=120000_random_state=3001' --n=120000 --num_workers=0 --random_state=3001 --save" 
)

eval "${experiments[$SLURM_ARRAY_TASK_ID]}"

conda deactivate
